services:
  icon-generator:
    image: boring-avatars-services
    build:
      context: ./nodejs
      dockerfile: Dockerfile
    container_name: icon-generator
    ports:
      - 3000:3000

  web:
    image: boring-avatars-web
    build:
      context: ./ruby
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 4567:4567
    environment:
      AVATAR_SERVICES_HOST: icon-generator
      AVATAR_SERVICES_PORT: 3000
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - type: bind
        source: ./ruby
        target: /app

  redis:
    image: redis:7.4.2
    container_name: redis
    ports:
      - 6379:6379
    