services:
  web:
    image: blog:latest
    container_name: blog_web
    build:
      context: .
      dockerfile: Dockerfile.development
    stdin_open: true
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command:
      bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: blog_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  mail:
    image: schickling/mailcatcher
    container_name: blog_mail
    ports:
      - 1025:1025
      - 1080:1080

volumes:
  bundle:
  db_data: