services:
  web:
    image: nextjs:latest
    container_name: nextjs
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
